language: python 
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests .
notifications:
  email:
    recipients:
      - rainer.kujala@gmail.com
      - christoffer.weckstrom@aalto.fi
    on_success: never # default: change
    on_failure: always # default: always
